--- #YAML:1.0
name:               DBIx-Class-ResultSet-Atomic
version:            0.005
abstract:           Atomic alternative to update_or_create()
author:
    - Peter Corlett <abuse@cabal.org.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBIx::Class:  0.081
    Test::More:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
